### ISSUE TITLE
Error while setting up hacs-minerstat platform for sensor

### ISSUE THREAD

**Issue by danielfinans** [gilsonmandalogo/hacs-minerstat#5]
2021-06-21 23:26:08 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up hacs-minerstat platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hacs-minerstat/sensor.py", line 27, in setup_platform
add_devices([Minerstat(hass, config)])
File "/config/custom_components/hacs-minerstat/sensor.py", line 37, in __init__
self.update()
File "/config/custom_components/hacs-minerstat/sensor.py", line 60, in update
self._status = data[self._config[CONF_RIG_NAME]]["info"]["status"]
KeyError: '_NAME-OF-RIG (edited)_'

**Comment by Kirbo** [comment]
See your miners name here:
https://api.minerstat.com/v2/stats/accessKeyHere/

The Rig name is case sensitive.
